function [varargout]=statbox(varargin)
%STATBOX (v2.0)
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Declare globals
% Global handles and variables for GUI operation

% -- Handles for figure and GUI panels
global guifig import_pan stat_pan kde_pan dms_pan export_pan

% > -- Handles for dynamic text boxes, table, pop-up menu and axes
global  

% -------------------------------------------------------------------------
% Check if input variable exists and declare 'filepath'
filepath='C:\Users\Jorge\Documents\PhD\Tese\SCBL\Aggregates to read\';
if nargin==1
    if ischar(varargin{1})==1
        filepath=varargin{1};
    end
end

% Create GUI
guifig=figure('Visible','off',...
    'Name','StatAnalysis',...
    'NumberTitle','off',...
    'Resize','off',...
    'Units','characters',...
    'Color',[0.941,0.941,0.941],...
    'Position',[20,4,213,55],...
    'WindowStyle','modal');

% Build components
%   -- Panels and axes
import_pan=uipanel('Title','Import data',...
    'Units','Characters',...
    'Position',[0.4,50.385,211.2,3.846],...
    'FontName','MS Sans Serif',...
    'FontSize',10,...
    'FontWeight','Bold');

stat_pan=uipanel('Title','Data statistical analysis',...
    'Units','Characters',...
    'Position',[0.4,34.231,58.6,16.154],...
    'FontName','MS Sans Serif',...
    'FontSize',10,...
    'FontWeight','Bold');

kde_pan=uipanel('Title','Kernel density estimation',...
    'Units','Characters',...
    'Position',[59.6,34.231,65.8,16.154],...
    'FontName','MS Sans Serif',...
    'FontSize',10,...
    'FontWeight','Bold');

dms_pan=uipanel('Title','Diameter minimum span analysis',...
    'Units','Characters',...
    'Position',[126,34.231,52,16.154],...
    'FontName','MS Sans Serif',...
    'FontSize',10,...
    'FontWeight','Bold');

export_pan=uipanel('Title','Export',...
    'Units','Characters',...
    'Position',[178.6,34.231,33.2,16.154],...
    'FontName','MS Sans Serif',...
    'FontSize',10,...
    'FontWeight','Bold');

plot_ax=axes('Color',[1,1,1],...
    'Units','characters',...
    'Position',[12.5,3,197.5,30],...
    'XLim',[0,500],...
    'XTick',[0,50,100,150,200,250,300,350,400,450,500],...
    'YLim',[0,0.03],...
    'YTick',[0,0.005,0.01,0.015,0.02,0.025,0.03]);...
    xlabel(plot_ax,'Diameter (\mum)','FontWeight','bold'),...
    ylabel(plot_ax,'Density','FontWeight','bold')
    

    

% Initialize GUI
set(guifig,'Visible','On')



% Set callback handles


% Set output arguments

uiwait 
varargout={};

end